# Generated by Django 3.2.16 on 2022-12-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pseudo',
        ),
    ]
